name: Deploy versioned docs

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      
      - name: Build versioned docs
        env:
          ASTRO_BASE: "/cqtkit-docs/versions/${{ steps.vars.outputs.TAG }}/"
          ASTRO_SITE: "https://a2-ai.github.io/cqtkit-docs/versions/${{ steps.vars.outputs.TAG }}/"
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          destination_dir: docs/versions/${{ steps.vars.outputs.TAG }}
          keep_files: true