name: Build & deploy docs for each Git tag

on:
  push:
    tags: ['v*']        # fires on v0.0.1, v0.0.2, etc.
  workflow_dispatch:    # manual back-fill if you like

permissions:
  contents: write       # needed to push to gh-pages
  pages:    write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get all version tags
        id: all-tags
        run: |
          ALL_TAGS=$(git tag -l 'v*' | sort -V | tr '\n' ' ' | sed 's/[[:space:]]*$//')
          echo "tags=$ALL_TAGS" >> $GITHUB_OUTPUT
          echo "Found tags: $ALL_TAGS"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Build all versions with latest versions.ts
        run: |
          # Get the latest versions.ts from main
          git fetch origin main --depth=1
          LATEST_VERSIONS=$(git show origin/main:src/data/versions.ts)
          
          # Create site directory structure once
          mkdir -p site/docs/versions
          
          # Build each version
          for tag in ${{ steps.all-tags.outputs.tags }}; do
            echo "Building version $tag..."
            
            # Reset any changes and checkout the tag (but keep site/ directory)
            git checkout .
            git checkout $tag
            
            # Clean this version's directory to avoid ghost pages
            TAG_SLUG=${tag#v}
            rm -rf site/docs/versions/$TAG_SLUG
            
            # Install dependencies for this version
            npm ci
            
            # Replace versions.ts with latest from main
            echo "$LATEST_VERSIONS" > src/data/versions.ts
            
            # Build this version
            ASTRO_BASE="/cqtkit-docs/versions/$TAG_SLUG/" \
            ASTRO_SITE="https://a2-ai.github.io/cqtkit-docs/versions/$TAG_SLUG/" \
            npm run build
            
            # Copy to site tree
            mkdir -p site/docs/versions/$TAG_SLUG
            cp -a dist/. site/docs/versions/$TAG_SLUG/
            
            echo "Completed build for $tag"
          done
          
          # Create redirect to latest version
          LATEST_TAG=$(echo "${{ steps.all-tags.outputs.tags }}" | tr ' ' '\n' | grep -v '^[[:space:]]*$' | tail -n1)
          LATEST_SLUG=${LATEST_TAG#v}
          
          cat > site/docs/index.html <<EOF
          <!doctype html>
          <meta http-equiv="refresh"
          content="0; url=/cqtkit-docs/versions/$LATEST_SLUG/">
          <title>Redirecting…</title>
          <p>Redirecting to documentation $LATEST_SLUG…</p>
          EOF
          
          # Add .nojekyll file for GitHub Pages
          touch site/docs/.nojekyll

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
          keep_files: true