name: Deploy versioned docs

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      
      - name: Build docs
        run: npx astro build --base=/cqtkit-docs/versions/${{ env.VERSION }}

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Fetch gh-pages or create it
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          
          # Add this version
          mkdir -p versions/${{ env.VERSION }}
          cp -r dist/* versions/${{ env.VERSION }}/
          
          # Add .nojekyll
          touch .nojekyll
          
          # Commit and push
          git add .
          git commit -m "Add version ${{ env.VERSION }}"
          git push origin gh-pages
