name: Build & deploy docs for each Git tag

on:
  push:
    tags: ['v*']        # fires on v0.0.1, v0.0.2, etc.
  workflow_dispatch:    # manual back-fill if you like

permissions:
  contents: write       # needed to push to gh-pages
  pages:    write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive version slug
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      
      - name: Astro build for ${{ steps.vars.outputs.TAG }}
        run: npx astro build --base=/cqtkit-docs/versions/${{ steps.vars.outputs.TAG }} --site=https://${{ github.repository_owner }}.github.io/cqtkit-docs/versions/${{ steps.vars.outputs.TAG }}

      - name: Copy version into site tree and add .nojekyll
        run: |
          # Create site directory and subdirectories
          mkdir -p site/versions/${{ steps.vars.outputs.TAG }}
          
          # Copy build to version directory
          cp -a dist/* site/versions/${{ steps.vars.outputs.TAG }}/
          
          # Create .nojekyll files to prevent Jekyll processing
          touch site/.nojekyll
          touch site/versions/${{ steps.vars.outputs.TAG }}/.nojekyll
          
          # Create redirect from root
          cat > site/index.html <<EOF
          <!doctype html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=/cqtkit-docs/versions/${{ steps.vars.outputs.TAG }}/">
            <title>Redirecting…</title>
          </head>
          <body>
            <p>Redirecting to documentation ${{ steps.vars.outputs.TAG }}…</p>
          </body>
          </html>

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
          keep_files: true
