name: Check Links in Docs

on:
  push:
    branches: ["**"]   # run on every branch push
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    name: Link Checker (HEAD)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build HEAD
        run: |
          set -euo pipefail

          BRANCH="${GITHUB_REF_NAME:-head}"
          SHORTSHA="$(git rev-parse --short HEAD)"
          SLUG="$(echo "$BRANCH" | tr '/._ ' '-')-$SHORTSHA"
          echo "Building HEAD -> slug=$SLUG"

          # Clean & prep output tree
          rm -rf "site/docs/versions/$SLUG"
          mkdir -p "site/docs/versions/$SLUG"

          # Install & build
          npm ci
          ASTRO_BASE="/cqtkit-docs/versions/$SLUG/" \
          ASTRO_SITE="https://a2-ai.github.io/cqtkit-docs/versions/$SLUG/" \
          npm run build

          # Copy build output into site tree
          cp -a dist/. "site/docs/versions/$SLUG/"

          # Root redirect to this build (optional; remove if you don't want it on non-main)
          cat > site/docs/index.html <<EOF
          <!doctype html>
          <meta http-equiv="refresh" content="0; url=/cqtkit-docs/versions/$SLUG/">
          <title>Redirecting…</title>
          <p>Redirecting to documentation $SLUG…</p>
          EOF

          # Disable Jekyll on Pages
          touch site/docs/.nojekyll

      - name: Link check (Linkinator)
        run: |
          npx --yes linkinator "site/docs/**/*.html" \
            --recurse \
            --serverRoot site/docs \
            --skip "https://github.com/*"

